### ISSUE TITLE
pybullet.error: Not connected to physics server

### ISSUE THREAD

**Issue by leeivan1007** [google-research/ravens#2]
I run the code

`python ravens/demos.py  --assets_root=./ravens/environments/assets/ --disp=True --task=block-insertion --mode=test --n=100
`

When disp is True, the p.SHARED_MEMORY is True.

`client = p.connect(p.SHARED_MEMORY if disp else p.DIRECT)`

then run

`file_io = p.loadPlugin('fileIOPlugin', physicsClientId=client)

`
**print  'pybullet.error: Not connected to physics server.' )**

Something should I run first? Maybe other physics server. 

![image](https://user-images.githubusercontent.com/14324351/102572719-c6d04500-4127-11eb-8af7-886335743148.png)

**Comment by andyzeng** [comment]
Thanks for the catch. Swap for `p.SHARED_MEMORY` for `p.GUI`. We'll add a hotfix.
If you'd still like to run with shared memory, run `python3 -m pybullet_utils.runServer&` in a separate terminal window.

**Comment by leeivan1007** [comment]
Now it look like great, thank you!
