### ISSUE TITLE
Small typo in README installation step 3

### ISSUE THREAD

**Issue by MandiZhao** [google-research/ravens#8]
Thanks for the code release! Spotted a very minor typo in the setup instruction:

Step 3. Recommended: install GPU acceleration with NVIDIA CUDA 10.1 and cuDNN 7.6.5 for Tensorflow.
First line
`./oss_scipts/install_cuda.sh` should be `./oss_scripts/install_cuda.sh`

**Comment by ayzaan** [comment]
Thank you, fixed in e3c52257c02415af3cf48cccc866c1ee5445318a
